<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-12T18:50:04 COT" name="Default suite" finished-at="2023-05-12T18:50:14 COT" duration-ms="9974">
    <groups>
    </groups>
    <test started-at="2023-05-12T18:50:04 COT" name="Default test" finished-at="2023-05-12T18:50:14 COT" duration-ms="9974">
      <class name="test.appointments.UserAppointmentTests">
        <test-method is-config="true" signature="setup()[pri:0, instance:test.appointments.UserAppointmentTests@2bbf180e]" started-at="2023-05-12T18:50:04 COT" name="setup" finished-at="2023-05-12T18:50:08 COT" duration-ms="4181" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="deleteAppointment()[pri:0, instance:test.appointments.UserAppointmentTests@2bbf180e]" started-at="2023-05-12T18:50:08 COT" name="deleteAppointment" finished-at="2023-05-12T18:50:13 COT" duration-ms="5549" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at pages.AppointmentPage.checkAppointment(AppointmentPage.java:70)
at test.appointments.UserAppointmentTests.deleteAppointment(UserAppointmentTests.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteAppointment -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:test.appointments.UserAppointmentTests@2bbf180e]" started-at="2023-05-12T18:50:13 COT" name="teardown" finished-at="2023-05-12T18:50:14 COT" duration-ms="212" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- test.appointments.UserAppointmentTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
